### ISSUE TITLE
First step fails

### ISSUE THREAD

**Issue by dstarr** [microsoftgraph/msgraph-training-reactspa#62]
### Where did you get the code?
- [X ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

https://docs.microsoft.com/en-us/graph/tutorials/react

### Describe the bug

Can't successfully launch generated app.

Works without typescript flag

### To Reproduce

1. I run `npx create-react-app@3.4.1 graph-tutorial --template typescript`
1. Run `npm start`
1. Get error

### Expected behavior

Browser opens

### Desktop

MacOS
bash
Edge Browser

### Additional context

I made sure to use the 12.16.1 version of Node

This is the resulting error message.

```
10:31 $ npm start

> graph-tutorial@0.1.0 start /Users/davidstarr/projects/rjsgraphapi/graph-tutorial
> react-scripts start

/Users/davidstarr/projects/rjsgraphapi/graph-tutorial/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/Users/davidstarr/projects/rjsgraphapi/graph-tutorial/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/Users/davidstarr/projects/rjsgraphapi/graph-tutorial/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graph-tutorial@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
```

**Comment by jasonjoh** [comment]
Hmm. This is all generic React stuff, nothing special (see https://create-react-app.dev/docs/getting-started#creating-a-typescript-app). The error seems to indicate an issue with TypeScript on your machine. I did some searching and found:

https://arbaz5256.medium.com/typeerror-cannot-assign-to-read-only-property-jsx-of-object-object-5caeaaad1b5c
https://github.com/facebook/create-react-app/issues/9868

**Comment by dstarr** [comment]
Okay, thank you very much for poking around on it.
